openapi: '3.0.3'
info:
  title: 量潮用户鉴权平台
  version: '0.1.0-alpha.1'
servers:
  - url: https://auth.quanttide.com/
paths:
  /users/signup/:
    $ref: paths/signup.yml
  /users/signin/:
    $ref: paths/signin.yml
  /users/signin-vcode/:
    post:
      responses:
        '200':
          description: OK
  /users/token/jwk/:
    post:
      responses:
        '200':
          description: OK
  /users/token/refresh/:
    post:
      responses:
        '200':
          description: OK